url: http://rubysec.com
title: RubySec
subtitle: Providing security resources for the Ruby community
author: RubySec
simple_search: https://www.google.com/search
description: Advisory database of security vulnerabilities found in Ruby projects

exclude:
  - _advisories
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor

gems:
  - octopress-filters

subscribe_rss: /atom.xml
email: rubysec-announce@googlegroups.com

permalink: /advisories/:title/
category_dir: advisories/categories
markdown: rdiscount
highlighter: pygments

paginate: 10                    # Posts per page on the blog index
pagination_dir: advisories      # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5                 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

twitter_user: rubysec
twitter_tweet_button: true
